---
- hosts: servers
  vars:
  - warName: java-example.war
  - warRemotePath: /var/lib/tomcat9/webapps
 

  tasks:
    - name: Install Java/Jdk
      apt: name=openjdk-11-jre-headless status=started
      
    - name: Install Tomcat9
      apt: name=tomcat9 status=started
      
    - name: Copy WAR to Remote server
      copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
   
